resources:
  pipelines:
    - pipeline: bluefalcon # Name of the pipeline resource.
      source: simpaccsolutions.bluefalcon # The name of the pipeline referenced by this pipeline resource.
      project: SimpleAndAccurate # Required only if the source pipeline is in another project
      trigger: true # Run app-ci pipeline when any run of security-lib-ci completes
    - pipeline: greenfalcon # Name of the pipeline resource.
      source: simpaccsolutions.greenfalcon # The name of the pipeline referenced by this pipeline resource.
      project: SimpleAndAccurate # Required only if the source pipeline is in another project
      trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

variables:
  - name: triggerBranch
    value: $[coalesce(resources.pipeline.bluefalcon.sourceBranch, resources.pipeline.greenfalcon.sourceBranch, variables['Build.SourceBranch'])]
  - name: triggerPipeline
    value: $[coalesce(resources.pipeline.bluefalcon.pipelineName, resources.pipeline.greenfalcon.pipelineName, 'direct')]

stages:
  - stage: Development
    displayName: "Development Environment"
    condition: |
      and(
        ne(variables['Build.Reason'], 'PullRequest'),
        or(
          eq(variables['triggerBranch'], 'refs/heads/main'),
          startsWith(variables['triggerBranch'], 'refs/heads/dev/')
        ),
        not(startsWith(variables['triggerBranch'], 'refs/heads/test/')),
        not(startsWith(variables['triggerBranch'], 'refs/heads/prod/'))
      )
    jobs:
      - job: DevJob
        displayName: "Development Job"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - bash: |
              echo "Running in Development environment"
              echo "Triggered by pipeline: $(triggerPipeline)"
              echo "Triggered by branch: $(triggerBranch)"
            displayName: "Print Development Environment"

  - stage: Test
    displayName: "Test Environment"
    condition: |
      and(
        ne(variables['Build.Reason'], 'PullRequest'),
        or(
          startsWith(variables['triggerBranch'], 'refs/heads/test/'),
          startsWith(variables['triggerBranch'], 'refs/heads/prod/')
        )
      )
    jobs:
      - job: TestJob
        displayName: "Test Job"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - bash: |
              echo "Running in Test environment"
              echo "Triggered by pipeline: $(triggerPipeline)"
              echo "Triggered by branch: $(triggerBranch)"
            displayName: "Print Test Environment"

  - stage: Production
    displayName: "Production Environment"
    dependsOn: Test
    condition: |
      and(
        ne(variables['Build.Reason'], 'PullRequest'),
        succeeded('Test'),
        startsWith(variables['triggerBranch'], 'refs/heads/prod/')
      )
    jobs:
      - job: ProdJob
        displayName: "Production Job"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - bash: |
              echo "Running in Production environment"
              echo "Triggered by pipeline: $(triggerPipeline)"
              echo "Triggered by branch: $(triggerBranch)"
            displayName: "Print Production Environment"
